### ISSUE TITLE
Meson Build Occasional Fails due to missing internal dependencies

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1023]
unit test can be built before preprocessing ORC files. Please avoid this by declaring dependencies.

```
[94/111] Compiling cpp object 'tests/unittest_plugins@exe/nnstreamer_plugins_unittest_plugins.cpp.o'
FAILED: tests/unittest_plugins@exe/nnstreamer_plugins_unittest_plugins.cpp.o 
c++  '-Itests/unittest_plugins@exe' '-Itests' '-I../tests' '-Igst/nnstreamer' '-I../gst/nnstreamer' '-I/usr/include/glib-2.0' '-I/usr/lib/x86_64-linux-gnu/glib-2.0/include' '-I/usr/include/gstreamer-1.0' '-I/usr/lib/x86_64-linux-gnu/gstreamer-1.0/include' '-I/usr/include/orc-0.4' '-I/usr/src/gtest' '-fdiagnostics-color=always' '-pipe' '-D_FILE_OFFSET_BITS=64' '-Werror' '-std=c++11' '-DVERSION="0.1.0"' '-DHAVE_ORC=1' '-DENABLE_TENSORFLOW_LITE=1' '-g' '-O2' '-fstack-protector-strong' '-Wformat' '-Werror=format-security' '-Wdate-time' '-D_FORTIFY_SOURCE=2' '-pthread' '-MMD' '-MQ' 'tests/unittest_plugins@exe/nnstreamer_plugins_unittest_plugins.cpp.o' '-MF' 'tests/unittest_plugins@exe/nnstreamer_plugins_unittest_plugins.cpp.o.d' -o 'tests/unittest_plugins@exe/nnstreamer_plugins_unittest_plugins.cpp.o' -c ../tests/nnstreamer_plugins/unittest_plugins.cpp
../tests/nnstreamer_plugins/unittest_plugins.cpp:2099:65: fatal error: ../../gst/nnstreamer/tensor_transform/transform-orc.h: No such file or directory
compilation terminated.
[95/111] Generating symbol file 'gst/nnstreamer/nnstreamer@sha/gst/nnstreamer/libnnstreamer.so.symbols'.
FAILED: gst/nnstreamer/nnstreamer@sha/gst/nnstreamer/libnnstreamer.so.symbols 
"/usr/bin/python3" "/usr/share/meson/meson" --internal symbolextractor gst/nnstreamer/libnnstreamer.so 'gst/nnstreamer/nnstreamer@sha/gst/nnstreamer/libnnstreamer.so.symbols' 
Traceback (most recent call last):
  File "/usr/share/meson/meson", line 37, in <module>
    sys.exit(main())
  File "/usr/share/meson/meson", line 34, in main
    return mesonmain.run(launcher, sys.argv[1:])
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 260, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 248, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/share/meson/mesonbuild/scripts/symbolextractor.py", line 111, in run
    gen_symbols(libfile, outfile, options.cross_host)
  File "/usr/share/meson/mesonbuild/scripts/symbolextractor.py", line 98, in gen_symbols
    linux_syms(libfilename, outfilename)
  File "/usr/share/meson/mesonbuild/scripts/symbolextractor.py", line 63, in linux_syms
    raise RuntimeError('Readelf does not work')
RuntimeError: Readelf does not work
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 67, in apport_excepthook
    binary = os.path.realpath(os.path.join(os.getcwd(), sys.argv[0]))
FileNotFoundError: [Errno 2] No such file or directory

Original exception was:
Traceback (most recent call last):
  File "/usr/share/meson/meson", line 37, in <module>
    sys.exit(main())
  File "/usr/share/meson/meson", line 34, in main
    return mesonmain.run(launcher, sys.argv[1:])
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 260, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 248, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/share/meson/mesonbuild/scripts/symbolextractor.py", line 111, in run
    gen_symbols(libfile, outfile, options.cross_host)
  File "/usr/share/meson/mesonbuild/scripts/symbolextractor.py", line 98, in gen_symbols
    linux_syms(libfilename, outfilename)
  File "/usr/share/meson/mesonbuild/scripts/symbolextractor.py", line 63, in linux_syms
    raise RuntimeError('Readelf does not work')
RuntimeError: Readelf does not work
[96/111] Compiling cpp object 'nnstreamer_example/example_object_detection_tensorflow/nnstreamer_example_object_detection_tensorflow@exe/nnstreamer_example_object_detection_tensorflow.cc.o'
FAILED: nnstreamer_example/example_object_detection_tensorflow/nnstreamer_example_object_detection_tensorflow@exe/nnstreamer_example_object_detection_tensorflow.cc.o 
c++  '-Innstreamer_example/example_object_detection_tensorflow/nnstreamer_example_object_detection_tensorflow@exe' '-Innstreamer_example/example_object_detection_tensorflow' '-I../nnstreamer_example/example_object_detection_tensorflow' '-Igst/nnstreamer' '-I../gst/nnstreamer' '-I/usr/include/glib-2.0' '-I/usr/lib/x86_64-linux-gnu/glib-2.0/include' '-I/usr/include/gstreamer-1.0' '-I/usr/lib/x86_64-linux-gnu/gstreamer-1.0/include' '-I/usr/include/cairo' '-I/usr/include/pixman-1' '-I/usr/include/freetype2' '-I/usr/include/libpng12' '-fdiagnostics-color=always' '-pipe' '-D_FILE_OFFSET_BITS=64' '-Werror' '-std=c++11' '-DVERSION="0.1.0"' '-DHAVE_ORC=1' '-DENABLE_TENSORFLOW_LITE=1' '-g' '-O2' '-fstack-protector-strong' '-Wformat' '-Werror=format-security' '-Wdate-time' '-D_FORTIFY_SOURCE=2' '-pthread' '-MMD' '-MQ' 'nnstreamer_example/example_object_detection_tensorflow/nnstreamer_example_object_detection_tensorflow@exe/nnstreamer_example_object_detection_tensorflow.cc.o' '-MF' 'nnstreamer_example/example_object_detection_tensorflow/nnstreamer_example_object_detection_tensorflow@exe/nnstreamer_example_object_detection_tensorflow.cc.o.d' -o 'nnstreamer_example/example_object_detection_tensorflow/nnstreamer_example_object_detection_tensorflow@exe/nnstreamer_example_object_detection_tensorflow.cc.o' -c ../nnstreamer_example/example_object_detection_tensorflow/nnstreamer_example_object_detection_tensorflow.cc
../nnstreamer_example/example_object_detection_tensorflow/nnstreamer_example_object_detection_tensorflow.cc:595:1: fatal error: opening dependency file nnstreamer_example/example_object_detection_tensorflow/nnstreamer_example_object_detection_tensorflow@exe/nnstreamer_example_object_detection_tensorflow.cc.o.d: No such file or directory
 }
 ^
compilation terminated.
```

**Comment by jaeyun-jung** [comment]
PR #1034
add dependency for generated files (nnstreamer_dep)

**Comment by jaeyun-jung** [comment]
supposed this issue has been fixed with a dependency of generated files
