### ISSUE TITLE
[Sink/Unittest] Sink unittest hangs with valgrind

### ISSUE THREAD

**Issue by kparichay** [nnsuite/nnstreamer#1369]
Unittest sink testcase hangs sometimes with valgrind (I will guess 3 out of 10 times) particularly at test `tensor_stream_test.octet_current_ts`. I cannot reproduce the issue of hanging without valgrind.

You can run the valgrind with the test case using the command `valgrind ./tests/unittest_sink --gst-plugin-path=.` from the build directory.

The backtrace and threads info while hanging is as follows:
```
(gdb) bt
#0  0x00000000063e174d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00000000050df38c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00000000050df712 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x000000000042a985 in tensor_stream_test_octet_current_ts_Test::TestBody (this=0x867e100) at ../tests/nnstreamer_sink/unittest_sink.cpp:2439
#4  0x00000000004851fa in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void> (object=0x867e100, 
    method=&virtual testing::Test::TestBody(), location=0x49c33b "the test body") at /usr/src/gtest/src/gtest.cc:2078
#5  0x000000000048041d in testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=0x867e100, 
    method=&virtual testing::Test::TestBody(), location=0x49c33b "the test body") at /usr/src/gtest/src/gtest.cc:2114
#6  0x0000000000466260 in testing::Test::Run (this=0x867e100) at /usr/src/gtest/src/gtest.cc:2151
#7  0x0000000000466a92 in testing::TestInfo::Run (this=0x8288ef0) at /usr/src/gtest/src/gtest.cc:2326
#8  0x00000000004670f9 in testing::TestCase::Run (this=0x8280ed0) at /usr/src/gtest/src/gtest.cc:2444
#9  0x000000000046dfd4 in testing::internal::UnitTestImpl::RunAllTests (this=0x827e6d0) at /usr/src/gtest/src/gtest.cc:4315
#10 0x000000000048614d in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x827e6d0, 
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x46dd1c <testing::internal::UnitTestImpl::RunAllTests()>, location=0x49cbd0 "auxiliary test code (environments or event listeners)") at /usr/src/gtest/src/gtest.cc:2078
#11 0x000000000048125d in testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x827e6d0, 
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x46dd1c <testing::internal::UnitTestImpl::RunAllTests()>, location=0x49cbd0 "auxiliary test code (environments or event listeners)") at /usr/src/gtest/src/gtest.cc:2114
#12 0x000000000046cbcc in testing::UnitTest::Run (this=0x6c4200 <testing::UnitTest::GetInstance()::instance>) at /usr/src/gtest/src/gtest.cc:3926
#13 0x000000000045749e in RUN_ALL_TESTS () at /usr/include/gtest/gtest.h:2288
#14 0x0000000000455d44 in main (argc=1, argv=0xffefff298) at ../tests/nnstreamer_sink/unittest_sink.cpp:4438
(gdb) info threads
  Id   Target Id         Frame 
* 1    Thread 1798 (tid 1 VgTs_WaitSys) 0x00000000063e174d in poll () at ../sysdeps/unix/syscall-template.S:84
  2    Thread 1809 (tid 4 VgTs_WaitSys appsrc:src) 0x00000000063e1811 in __GI_ppoll (fds=0x8dae070, nfds=1, timeout=<optimized out>, sigmask=0x0)
    at ../sysdeps/unix/sysv/linux/ppoll.c:50
``` 

Can you please take a look.

**Comment by jaeyun-jung** [comment]
PR #1374 to push the buffers into appsrc with delayed timer.
Also I added code to check eos in this pr.

**Comment by jaeyun-jung** [comment]
IMO, this issue was fixed after adding timer to push buffer into appsrc. Close this issue.
