### ISSUE TITLE
[CI/Apptest] all PRs are failed suddenly.

### ISSUE THREAD

**Issue by leemgs** [nnsuite/nnstreamer#924]
### Screenshot
![image](https://user-images.githubusercontent.com/82404/49123562-5f56bb00-f2fc-11e8-845e-edad5ab7747e.png)

**Comment by leemgs** [comment]
### Analysis after reverting

```bash

[DEBUG] Starting nnstreamer_example_filter test...

(gst-plugin-scanner:11031): GStreamer-WARNING **: Failed to load plugin '/var/www/html/nnstreamer/TAOS-CI/ci/repo-workers/pr-checker/888-201811281000580.28173995018005-9c781774359ae6fd6d6ae0ab1037c964b71563d3/nnstreamer/lib/libnnstreamer.so': libtensor_filter_tflitecore.so: cannot open shared object file: No such file or directory

(nnstreamer_example_filter:11028): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(nnstreamer_example_filter:11028): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(nnstreamer_example_filter:11028): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed

[DEBUG] Starting nnstreamer_example_filter.py test...
Traceback (most recent call last):
  File "nnstreamer_example_filter.py", line 239, in <module>
    example.run_example()
  File "nnstreamer_example_filter.py", line 76, in run_example
    'tensor_filter framework=tensorflow-lite model=' + self.tflite_model + ' ! '
GLib.Error: gst_parse_error: no element "tensor_converter" (1)

[DEBUG] Starting nnstreamer_sink_example_play test...
```

**Comment by leemgs** [comment]
It seem that we have got the failure of apptest with latest PR. 
* @leemgs : The example_filter test is failed with latest PR. 
* @jaeyun-jung : Same above.

* Log message: 
```bash
 ./nnstreamer_example_filter 
nnapi error: unable to open library libneuralnetworks.so
libv4l2: error getting pixformat: Invalid argument
ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:cam_src: Internal data flow error.
Additional debug info:
gstbasesrc.c(2948): gst_base_src_loop (): /GstPipeline:pipeline0/GstV4l2Src:cam_src:
streaming task paused, reason not-negotiated (-4)
ubuntu@ip-172-31-27-164:~/nnstreamer/bin$ 

```

**Comment by leemgs** [comment]
### Unit test on ubuntu 16.04 x86_64 with /dev/video0 (fake camera)
```bash
## gstreamer: producer
$ gst-launch-1.0 videotestsrc ! v4l2sink device=/dev/video0

## gstreamer: consumer
$ gst-launch-1.0 v4l2src device=/dev/video0 ! xvimagesink
```
